# Generated by Django 5.1.4 on 2024-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmanager_model',
            name='phoneno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_model',
            name='phoneno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
