# Generated by Django 5.1.4 on 2024-12-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0003_alter_eventprogram_model_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaterials_model',
            name='Purchasematerial',
        ),
        migrations.AddField(
            model_name='eventmaterials_model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmaterials_model',
            name='imagematerial',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventprogram_model',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventmaterials_model',
            name='Eventid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.eventmanager_model'),
        ),
    ]
