# Generated by Django 5.1.4 on 2024-12-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0004_remove_eventmaterials_model_purchasematerial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='COURSE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.course_model'),
        ),
    ]
