# Generated by Django 5.1.4 on 2024-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0005_user_model_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_model',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
