# Generated by Django 5.1.4 on 2024-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0007_rename_email_course_model_coursename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
