# Generated by Django 5.1.4 on 2024-12-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0008_alter_course_model_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprogram_model',
            name='MANAGER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.eventmanager_model'),
        ),
    ]
