# Generated by Django 5.1.4 on 2024-12-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0009_eventprogram_model_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_model',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.teacher_model'),
        ),
    ]
