# Generated by Django 5.1.4 on 2025-01-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0010_alter_notification_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_model',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.login_model'),
        ),
    ]
