# Generated by Django 5.1.4 on 2025-01-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0011_notification_model_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_model',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='notification_model',
            name='TEACHER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.teacher_model'),
        ),
        migrations.AlterField(
            model_name='notification_model',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
