# Generated by Django 5.1.4 on 2025-01-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0012_remove_notification_model_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_model',
            old_name='subject',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='notification_model',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
