# Generated by Django 5.1.4 on 2025-01-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0014_video_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_model',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
