# Generated by Django 5.1.4 on 2025-01-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haagapp', '0015_alter_video_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_model',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fees_model',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fees_model',
            name='teacherid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Haagapp.teacher_model'),
        ),
    ]
